
volumes:
  dinx_local_postgres_data: {}
  dinx_local_postgres_data_backups: {}
  dinx_local_redis_data: {}
  dinx_local_fastapi_venv: {}


services:

  fastapi:
    build:
      context: ../..
      dockerfile: ./compose/local/fastapi/dockerfile
    image: dinx_local_fastapi
    container_name: dinx_local_fastapi
    volumes:
      - ../..:/code
      - dinx_local_fastapi_venv:/code/.venv
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ../../.envs/.local/.postgres
      - ../../.envs/.local/.fastapi

  postgres:
    build:
      context: ../..
      dockerfile: ./compose/prod/postgres/Dockerfile
    image: dinx_local_postgres
    container_name: dinx_local_postgres
    volumes:
      - dinx_local_postgres_data:/var/lib/postgresql/data
      - dinx_local_postgres_data_backups:/backups
    env_file:
      - ../../.envs/.local/.postgres
    ports:
    - "5432:5432"
