FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

WORKDIR /code

COPY pyproject.toml uv.lock /code/

RUN uv sync --frozen --no-dev --no-install-project

ENV PATH="/code/.venv/bin:$PATH"
ENV PYTHONPATH="/code"

COPY ./src /code/src
COPY main.py /code/main.py

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

